#!/bin/bash

CUR_DIR=$(pwd)

# Set the path custom-built LLVM binaries
LLVM_PATH="$CUR_DIR/llvm-project-14/bin"

# export LLVM HOME path 
export LLVM_HOME="$CUR_DIR/llvm-project-14"  

# Add LLVM_PATH to the current shell
export PATH="$LLVM_PATH:$PATH"

# Optionally print confirmation
echo "LLVM_HOME set to: $LLVM_HOME"
echo "LLVM binaries added to PATH: $LLVM_PATH"

