#!/bin/bash
# Find all staged .cpp and .h files and format them
files=$(find ./src ./tests -regex '.*\.[c|h]pp' )

if [ -n "$files" ]; then
    for file in $files; do
				echo $file
        clang-format -i "$file" # Format the file
        git add "$file" # Re-add to staging area after formatting
    done
fi

